print("Bootstrapping...")
fs.makeDir("/lib")
fs.makeDir("/startup")
fs.makeDir("/bin")
fs.makeDir("/opt")
fs.makeDir("/tmp")
fs.makeDir("/usr/local")
print("Installing UNIX path bootstrap...")
shell.run("wget https://gist.githubusercontent.com/tomodachi94/57b52cef2ad117c0b4130429dc80964a/raw/0dbe8a7ef58ac6f6a562410fafe7654301ffc678/unix-path-bootstrap.lua /bin/unix-path-bootstrap.lua")
shell.run("wget https://gist.githubusercontent.com/tomodachi94/57b52cef2ad117c0b4130429dc80964a/raw/0dbe8a7ef58ac6f6a562410fafe7654301ffc678/unix-path-bootstrap-startup.lua /startup/unix-path-bootstrap-startup.lua")
print("Installing sha2 library...")
shell.run("wget https://raw.githubusercontent.com/Egor-Skriptunoff/pure_lua_SHA/master/sha2.lua /lib/sha2.lua")
print("Installing CONU coreutils...")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/cp.lua /bin/cp.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/mkdir.lua /bin/mkdir.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/touch.lua /bin/touch.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/cat.lua /bin/cat.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/sha1sum.lua /bin/sha1sum.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/sha224sum.lua /bin/sha224sum.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/sha256sum.lua /bin/sha256sum.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/sha384sum.lua /bin/sha384sum.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/sha512sum.lua /bin/sha512sum.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/rm.lua /bin/rm.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/uname.lua /bin/uname.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/mv.lua /bin/mv.lua")
shell.run("wget https://raw.githubusercontent.com/CC-CONU/coreutils/main/pwd.lua /bin/pwd.lua")
print("Installing CASH")
shell.run("wget https://raw.githubusercontent.com/MCJack123/cash/master/cash.lua /bin/cash.lua")
shell.run("wget https://raw.githubusercontent.com/MCJack123/cash/master/env.lua /bin/env.lua")
